In [16]:
import torch
import time
import numpy as np
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

cuda


In [17]:
rand =  torch.randint(-100,100,(6,))
print(rand)

tensor([-42,  74, -74,  29,  33, -39])


In [18]:
tensor = torch.randn((3,2))
print(tensor)

tensor([[-1.9342, -0.4129],
        [ 1.6203,  0.2054],
        [-0.6474,  1.3904]])


In [19]:
zeros = torch.zeros(3,2)
print(zeros)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [20]:
linspace =  torch.linspace(1,6 , steps = 5)
print(linspace)

tensor([1.0000, 2.2500, 3.5000, 4.7500, 6.0000])


In [21]:
eye = torch.eye(4)
print(eye)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [28]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start =  time.time()

rand = (torch_rand1 @ torch_rand2)

end = time.time()

elapsed_time = end -start
print(f"{elapsed_time:.8f}")

start = time.time()

rand = np.multiply(np_rand1,np_rand2)
end = time.time()

elapsed_time = end -start

print(f"{elapsed_time:.8f}")

0.01901245
0.10894895


In [31]:
tensor = torch.tensor([1,2,3,4])
mew = torch.cat((tensor,torch.tensor([5])),dim = 0)
print(mew)

tensor([1, 2, 3, 4, 5])


### Triangular matrix

In [36]:
ones = torch.ones(6,6)

In [37]:
tri1 = torch.tril(ones)
print(tri1)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [38]:
tri2 = torch.triu(ones)
print(tri2)

tensor([[1., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.]])


### Transposing tensors

In [41]:
tensor = torch.zeros(2,3,4)
tt = tensor.transpose(0,2)
print(tt.shape)

torch.Size([4, 3, 2])


### Stacking tensors

In [42]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([5,6,7,8])
t3 = torch.tensor([9,10,11,12])

#Stacking the tensors along a new dimension
staceked_tensor = torch.stack([t1,t2,t3])
print(staceked_tensor)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


### Softmax and torch.nn

In [43]:
import torch.nn as nn
import torch.nn.functional as F

tensor = torch.tensor([1.,2.,3.])

softmax_output = F.softmax(tensor, dim=0)
print(softmax_output)   

tensor([0.0900, 0.2447, 0.6652])
